apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main-web
          image: specialops/devopsgym:2.3.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: regcred

