name: Build App
on:
 workflow_dispatch: 
 push:
   branches: 
     - main
   paths:
    - src/**
    - pom.xml

jobs:
  BuildApp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
      - name: Build 
        run: |
            mvn clean install

       
