name: Create Semantic Version Tags
on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install semver
        run: npm install --global semver

      - name: Determine current version
        id: version
        run: |
          VERSION=$(git describe --abbrev=0 --tags)
          echo "::set-output name=current_version::$VERSION"
          echo $current_version

      - name: Generate new version
        id: new_version
        run: |
          CURRENT_VERSION="${{ steps.version.outputs.current_version }}"
          NEW_VERSION=$(semver bump patch "$CURRENT_VERSION")
          echo "::set-output name=new_version::$NEW_VERSION"
          echo $new_version

      - name: Create tag
        run: |
          NEW_TAG="${{ steps.new_version.outputs.new_version }}"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
