name: Build-release
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
      - name: run tests
        run: |
            mvn test
      - name: Install semver
        run: npm install --global semver
      - name: Determine current version
        id: version
        run: |
          VERSION=$(git describe --abbrev=0 --tags)
          echo "::set-output name=current_version::$VERSION"

      - name: Determine bump type
        id: bump_type
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $COMMIT_MSG =~ BREAKING|Breaking|breaking ]]; then
            echo "bump_type=major" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG =~ FEAT|feat ]]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
          else
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          fi
          echo "bump_type for this commit is $bump_type"
      - name: Generate new version
        id: new_version
        run: |
          CURRENT_VERSION="${{ steps.version.outputs.current_version }}"
          BUMP_TYPE="${{ steps.bump_type.outputs.bump_type }}"
          if [[ $BUMP_TYPE == "major" ]]; then
            NEW_VERSION=$(semver -i major "$CURRENT_VERSION")
          elif [[ $BUMP_TYPE == "minor" ]]; then
            NEW_VERSION=$(semver -i minor "$CURRENT_VERSION")
          else
            NEW_VERSION=$(semver -i patch "$CURRENT_VERSION")
          fi
          echo "NEW_TAG=$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: Create tag
        run: |
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
      - name: Build and Publish war
        run: |
          mvn clean package 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build . -t specialops/devopsgym:$NEW_TAG
          docker push specialops/devopsgym:$NEW_TAG
  
  # release:
  #   runs-on: ubuntu-latest
  #   needs: publish-image 
  #   permissions: write-all
  #   steps:     
  #   - name: Create release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ steps.new_version.outputs.new_version }}
  #       release_name: Release ${{ steps.new_version.outputs.new_version }}
  #       draft: false
  #       prerelease: false