name: Build & Publish
on:
 workflow_dispatch: 
 push:
   branches: 
     - main
   paths:
    - src/**
    - pom.xml

jobs:
  BuildApp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
      - name: Build 
        run: |
            mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build . -t specialops/devopsgym:$GITHUB_RUN_NUMBER
          docker push specialops/devopsgym:$GITHUB_RUN_NUMBER

  release:
      runs-on: ubuntu-latest
      permissions: write-all
      name: GITHUB_TOKEN
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # required for github-action-get-previous-tag
  
        - name: Get previous tag
          id: previoustag
          uses: 'WyriHaximus/github-action-get-previous-tag@v1'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            fallback: 1.0.0  
  
        - name: Get next minor version
          id: semver
          uses: 'WyriHaximus/github-action-next-semvers@v1'
          with:
            version: ${{ steps.previoustag.outputs.tag }}
  
        - name: Create release
          id: create_release_id
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.semver.outputs.patch }}
            release_name: Release ${{ steps.semver.outputs.patch }}