name: Java CI
on:
 workflow_dispatch: 
 push:
   branches: 
     - main
jobs:
  BuildApp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
            cache: 'maven'

      - name: Build & publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
        run: |
            mvn --settings settings.xml deploy
