name: Build & Publish
on:
 workflow_dispatch: 
 push:
   branches: 
     - main
   paths:
    - src/**
    - pom.xml

jobs:
  BuildApp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' 
            java-version: '17'
      - name: Build 
        run: |
            mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build . -t specialops/devopsgym:$GITHUB_RUN_NUMBER
          docker push specialops/devopsgym:$GITHUB_RUN_NUMBER

  release:
    runs-on: ubuntu-latest
    needs: BuildApp
    permissions: write-all
    name: GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate branch diff file
        if: success()
        run: |
          echo "Head branch: ${GITHUB_HEAD_REF}"
          echo "Base branch: ${GITHUB_BASE_REF}"
          git log origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} > ./branch-diff.txt
      - name: Extract previous version
        if: success()
        run: |
          export PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
          echo "Previous version: ${PREVIOUS_VERSION}"
          echo "PREVIOUS_VERSION=${TAG}" > ${GITHUB_ENV}
      - name: Generate version number
        id: generate
        if: success()
        uses: juztcode/generate-semver@1.0.0
        with:
          branch-diff-file: ./branch-diff.txt
          previous-version: ${{ env.PREVIOUS_VERSION }}

      - name: Print version
        if: success()
        run: echo ${{ steps.generate.outputs.generated-version }}